[43기 이창섭] ADD: 장바구니 삭제 기능
wecode-bootcamp-korea/43-1st-4iz-backend pull request #15
Opened 2023-03-11 12:42 UTC by Chang9601

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 장바구니 삭제 기능

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사
  - 경로 변수인 제품 아이디와 장바구니 아이디
- product_carts 테이블의 product_id가 carts 테이블을 참조하는 외래키이기 때문에 먼저 삭제 후 carts 테이블에서 장바구니 삭제

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![server](https://user-images.githubusercontent.com/79137839/224485063-eaccd76b-30fc-419e-ac6f-047cb87e16bc.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
![delete-cart-postman](https://user-images.githubusercontent.com/79137839/224485113-c710ae49-614c-4ecc-870d-d6de637d0c77.png)

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![delete-cart-db](https://user-images.githubusercontent.com/79137839/224485122-81e26342-8dea-4720-ae22-7819e4176ba4.png)

<br />

## :: 기타 질문 및 특이 사항
- 다대다 관계를 가지는 테이블을 수정하기 때문에 트랜잭션을 사용했는데 다음과 같은 오류가 나옵니다. 구글링해도 어떻게 해야 할지 잘 모르겠습니다...
![lock-wait-error](https://user-images.githubusercontent.com/79137839/224485159-ccfdf115-4dda-42b8-91de-eccbb3aa73fd.png)

2023-03-13 09:33 UTC, kyeongraekim requested changes

2023-03-13 09:33 UTC, kyeongraekim commented on api/models/cartDao.js
> +      await dataSource.query(
- 해당 부분 함께 같이 본 내용이네요!~

2023-03-13 09:34 UTC, kyeongraekim requested changes

2023-03-13 09:34 UTC, kyeongraekim commented on api/models/cartDao.js
> +    let deletedRows = (
- 그리고 웹서비스 내에서의 자바스크립트 에서는 let과 var의 사용을 극히 줄이는 추세입니다. 
- 변함이 없는 const 등의 변수 선언 방법을 이용하여 보다 엄격한 변수, 데이터 관리를 보여주세요!~

2023-03-13 09:48 UTC, kyeongraekim requested changes

2023-03-13 09:48 UTC, kyeongraekim commented on api/models/cartDao.js
> +    deletedRows = (
- 현재 deletedRows를 변수삼아 재할당을 하고 있습니다.
- node.js 서버사이드 프로그래밍에서는 불필요한 재할당을 최대한 피해주는게 가독성, 유지보수, 성능면에서 더 좋은 우의를 점합니다. 
- const 와 같은 별도의 변수에 담아서 product_cart를 삭제하는 내역과 cart를 삭제하는 내역을 서로 다르게 확인할 수 있게 구분지어 주세요!

2023-03-13 09:48 UTC, kyeongraekim commented on api/models/cartDao.js
> +    if (deletedRows !== 0 && deletedRows !== 1) {
- 삭제하는 내역은 delete 문에서 하나의 row를 건드리며 삭제하는 내용을 의도하였기 때문에, !== 1 일경우에만 에러가 난다는 상황으로 이어져야 합니다.
- 만일 해당 내역이 없다는 경우라면 서비스 단에서 미리 에러를 핸들링해주셔서, 삭제할 내역이 없는 인자 데이터 값을 해당 Dao단으로 흘러들어오지 못하게 막아주세요!

2023-03-13 10:23 UTC, Chang9601 commented on api/models/cartDao.js
> +    if (deletedRows !== 0 && deletedRows !== 1) {
내역 확인은 따로 브랜치를 만들어서 하겠습니다.

2023-03-14 01:39 UTC, kyeongraekim approved these changes
LGTM!~

2023-03-14 01:39 UTC, merged