[43기 이창섭] ADD: 주문 추가 기능
wecode-bootcamp-korea/43-1st-4iz-backend pull request #19
Opened 2023-03-12 13:25 UTC by Chang9601

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 장바구니 목록의 제품을 주문하는 기능

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 주문 생성, 결제 생성, 배송 생성
- 주문 제품의 재고 개수 차감
- 장바구니 삭제
- 외래키로 연결되어 있기 때문에 트랜잭션 사용

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![server](https://user-images.githubusercontent.com/79137839/224547556-e0380ed2-9904-4140-8f1c-9db4ccb32685.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
![order-postman](https://user-images.githubusercontent.com/79137839/224547618-23ffed5d-4102-414c-884d-5571ca67a240.png)

3.. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![cart](https://user-images.githubusercontent.com/79137839/224547636-c305c6cc-2225-4b52-9ebe-a634b4f9021f.png)
![order](https://user-images.githubusercontent.com/79137839/224547638-626af4d3-0348-4f54-9e0c-21e823ae907d.png)
![payment](https://user-images.githubusercontent.com/79137839/224547639-bef53241-f60a-424e-bd84-54cda902d8ac.png)
![product-order](https://user-images.githubusercontent.com/79137839/224547644-c8613d09-d855-4857-bc2e-73e9c12eff84.png)
![shipment](https://user-images.githubusercontent.com/79137839/224547646-7216fa9c-81ed-45c6-9c41-8a7d5b830e29.png)

<br />

## :: 기타 질문 및 특이 사항
- 장바구니 삭제와 똑같은 코드를 사용했는데 여기서는 lock wait timeout 오류가 발생하지 않습니다. 왜 그런가요?

2023-03-13 04:58 UTC, kyeongraekim requested changes

2023-03-13 04:58 UTC, kyeongraekim commented on api/models/orderDao.js
> +  return randomString;
- 해당 임의의 랜덤 값을 문자열에 배정하는 내용에는 uuid4 와 같은 서로의 중복값이 나올 확률이 극히 적은 랜덤 메소드를 활용해보세요!

2023-03-13 04:58 UTC, kyeongraekim commented on api/models/orderDao.js
> +        [userId, 1, cart.option_id, `order ${cart.id}`, orderNumber]
- 현재 1과 같은 숫자는 하드코딩이 되어있는 것으로 판단됩니다.
- Object.freeze() 메소드를 이용하여 고정값의 status를 다른 별도의 파일에 enum의 형태로 선언하여서 해당 하드코딩들을 변경해보세요!

2023-03-13 04:58 UTC, kyeongraekim commented on api/models/orderDao.js
> +    carts.forEach(async (cart) => {
- 현재 내용은 for문이 한 번 돌 때마다 db를 히트하는 기획으로 되어있습니다.
- Bulk Insert 를 활용하는 방향으로 변경하여서 불필요한 db 연결을 최소화 해보세요!

2023-03-13 09:30 UTC, kyeongraekim requested changes

2023-03-13 09:30 UTC, kyeongraekim commented on api/models/orderDao.js
> +        await dataSource.query(
- 좀 전에 같이 디버깅 해드린 이 곳도 수정이 필요해보이네요! queryRunner가 아닌 dataSource로의 새로운 호출이 이루어 지고 있습니다~

2023-03-14 02:28 UTC, Chang9601 commented on api/models/orderDao.js
> +    carts.forEach(async (cart) => {
이 부분은 검색을 했는데 여러 테이블에 삽입 작업을 해서 어떻게 적용해야 할 지 잘 모르겠습니다.

2023-03-15 07:03 UTC, kyeongraekim approved these changes
LGTM!~

2023-03-15 07:03 UTC, merged