[43기 이창섭] ADD: DB 데이터 모델링
wecode-bootcamp-korea/43-1st-4iz-backend pull request #2
Opened 2023-03-07 10:14 UTC by Chang9601

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 데이터 모델링

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 프로젝트 데이터베이스에 필요한 테이블 생성 (사용자, 제품, 주문,  결제, 배송, 하위 카테고리, 제품 옵션, 장바구니)
  - 일대일: 주문-결제, 주문-배송
  - 일대다: 사용자-장바구니, 사용자-주문, 제품-제품 옵션
  - 다대다: 제품-하위 카테고리, 제품-장바구니, 제품-주문

<br />

## :: 테스트 결과 이미지
1. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![DB](https://user-images.githubusercontent.com/79137839/223392085-917401e7-f1ea-466c-a913-5fb013c362c7.png)
<br />

## :: 기타 질문 및 특이 사항
- 주문 상태는 ENUM을 사용했습니다.

2023-03-07 13:21 UTC, kyeongraekim requested changes

2023-03-07 13:21 UTC, kyeongraekim commented on db/migrations/20230307073601_create_users_table.sql
> +  phone_number VARCHAR(200) UNIQUE NOT NULL,
- 전화번호는 생각보다 번호이동과 변경이 잦게 일어나서, 실제 고객들 중 UNIQUE 제한 시 사용에 대한 제약이 생길 수 있는 신규 유입 고객이 있을 것으로 보이네요. 
- 전화번호에 대한 고유 설정은 없에주어도 좋을 것 같습니다!

2023-03-07 13:21 UTC, kyeongraekim commented on db/migrations/20230307074314_create_products_table.sql
> +  discount_rate INT DEFAULT 0,
- 할인율에 대한 내용이고 정수값을 책정할 예정이라면, rate값이 1이 되어야 곱셈을 할 때 기존 가격이 아무런 영향없이 출력될 수 있겠네요!

2023-03-07 13:21 UTC, kyeongraekim commented on db/migrations/20230307080009_create_product_options_table.sql
> +  size_name VARCHAR(100),
- color와 size에 대한 경우의 수를 모두 커버할 기획이라면 해당 options 테이블에서 색깔 명에 대한 varchar 만을 유지하거나(추후 필터링 시 필드값 내 문자열 이용), 아니면 color_id 만을 유지하거나(추후 필터링 시 외부 테이블의 정수 pk 값 이용)의 기획이 더 좋을 것 같아 보이네요! 둘다 유지하는 것은 동일 기능 데이터의 중첩으로 보여집니다!

- 추가로 product_options에는 products에서 관리하고 있는 quantity를 지우고 이곳 테이블로 끌고 들어와야 될 것 같습니다. 상품 사이즈, 칼라로 파생될 수 있는 다양한 경우의 수에 따라서, 재고 수량의 이력관리가 필요할 수 있겠네요!

2023-03-07 13:21 UTC, kyeongraekim commented on db/migrations/20230307080153_create_carts_table.sql
> +  sum DECIMAL(15, 3) NOT NULL,
- 가격의 총합임을 뜻하는 price_sum 정도로 수정변경해주세요!

2023-03-07 13:21 UTC, kyeongraekim commented on db/migrations/20230307080434_create_product_carts_table.sql
> +  INT id PRIMARY KEY AUTO_INCREMENT,
- 이곳은 "INT id" 로 다른 파일들과의 컨벤션이 align이 맞지 않아보이네요!

2023-03-07 13:21 UTC, kyeongraekim commented on db/migrations/20230307080627_create_orders_table.sql
> +  order_status ENUM("Pending", "Completed", "Shipped", "Cancelled", "Refunded"),
- 해당내용은 sql 선에서의 enum 보다 안내해드린 ERD 모델 예시와 같이 따로 테이블로 빼는 기획을 권장드립니다!

2023-03-07 13:21 UTC, kyeongraekim commented on db/migrations/20230307081440_create_product_orders_table.sql
> +  sum DECIMAL(20, 3) NOT NULL,
- 이곳도 가격을 나타내는 영어 표현을 꼭 넣어주세요!

2023-03-07 14:47 UTC, Chang9601 commented on db/migrations/20230307074314_create_products_table.sql
> +  discount_rate INT DEFAULT 0,
(1 - discount_rate / 100)를 사용하기 위해서 0을 기본값으로 설정했습니다.

2023-03-08 03:01 UTC, kyeongraekim reviewed
LGTM!~

2023-03-08 03:02 UTC, merged